import { $, downloadText, errorMessage, escapeHtml, formatDate, hoyISO, normClient, normNumber } from "./utils.js";
import {
  login,
  logout,
  observeAuth,
  register
} from "./auth.js";
import { createDelivery, migrateLegacy, removeDelivery, updateDelivery, watchDeliveries } from "./entregas-service.js";

const LEGACY_KEY="agroventas_rural_prado_2026_entregas";
let deliveries=[];let editingId=null;let stopWatch=null;let installPrompt=null;let cameraStream=null;let scanTimer=null;
const toast=(msg,error=false)=>{const t=$("toast");t.textContent=msg;t.classList.toggle("error",error);t.classList.add("show");clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.remove("show"),3200);};
const dataFrom=(prefix="e-")=>({cliente:$(prefix+"cliente").value.trim(),numero:$(prefix+"numero").value.trim(),tipo:$(prefix+"tipo").value,dia:$(prefix+"dia").value});
function validate(data,currentId=null){if(!data.cliente||!data.numero){toast("Completá el cliente y el número de entrada.",true);return false;}if(data.tipo==="Dia"&&!data.dia){toast("Indicá el día de acceso.",true);return false;}const d=deliveries.find(x=>x.id!==currentId&&normNumber(x.numero)===normNumber(data.numero));if(d){toast(`La entrada N.º ${data.numero} ya fue entregada a ${d.cliente}.`,true);return false;}return true;}
function toggleDay(prefix="e-"){const box=prefix==="e-"?$("campo-dia"):$("edit-campo-dia");box.hidden=$(prefix+"tipo").value!=="Dia";}
function sortedRows(rows){return rows.sort((a,b)=>`${b.fechaEntrega||""} ${b.horaEntrega||""}`.localeCompare(`${a.fechaEntrega||""} ${a.horaEntrega||""}`));}
function renderStats(){const today=hoyISO();$("stat-total").textContent=deliveries.length;$("stat-hoy").textContent=deliveries.filter(x=>x.fechaEntrega===today).length;$("stat-dia").textContent=deliveries.filter(x=>x.tipoAcceso==="Dia").length;$("stat-libre").textContent=deliveries.filter(x=>x.tipoAcceso==="Libre").length;}
function renderChart(){const c={};deliveries.forEach(x=>{const k=x.fechaEntrega||"Sin fecha";c[k]=(c[k]||0)+1;});const rows=Object.entries(c).sort((a,b)=>a[0].localeCompare(b[0])).slice(-8);if(!rows.length){$("grafico").innerHTML='<div class="empty">Todavía no hay datos.</div>';return;}const max=Math.max(...rows.map(x=>x[1]));$("grafico").innerHTML=rows.map(([d,n])=>`<div class="bar-row"><span>${formatDate(d)}</span><div class="bar-track"><div class="bar" style="width:${Math.max(8,n/max*100)}%"></div></div><strong>${n}</strong></div>`).join("");}
function filtered(){const q=$("buscar").value.trim().toLocaleLowerCase("es");const type=$("filtro-tipo").value;const date=$("filtro-fecha").value;return deliveries.filter(x=>(!q||x.cliente.toLocaleLowerCase("es").includes(q)||String(x.numero).toLocaleLowerCase("es").includes(q))&&(type==="Todos"||x.tipoAcceso===type)&&(!date||x.fechaEntrega===date));}
function renderTable(){const rows=filtered();$("contador-resultados").textContent=`${rows.length} resultado${rows.length===1?"":"s"}`;$("vacio-lista").hidden=rows.length>0;$("tabla-entregas").innerHTML=rows.map(x=>`<tr><td data-label="Cliente">${escapeHtml(x.cliente)}</td><td data-label="N.º">#${escapeHtml(x.numero)}</td><td data-label="Tipo"><span class="pill ${x.tipoAcceso==="Libre"?"free":"day"}">${x.tipoAcceso==="Libre"?"Pase libre":"Un día"}</span></td><td data-label="Acceso">${x.tipoAcceso==="Dia"?formatDate(x.diaAcceso):"Todos los días"}</td><td data-label="Entrega">${formatDate(x.fechaEntrega)} · ${escapeHtml(x.horaEntrega||"")}</td><td><div class="row-actions"><button class="mini-btn" data-edit="${x.id}">Editar</button><button class="mini-btn danger" data-del="${x.id}">Eliminar</button></div></td></tr>`).join("");document.querySelectorAll("[data-edit]").forEach(b=>b.onclick=()=>openEdit(b.dataset.edit));document.querySelectorAll("[data-del]").forEach(b=>b.onclick=()=>remove(b.dataset.del));}
const renderAll=()=>{renderStats();renderChart();renderTable();};
async function submitNew(e){e.preventDefault();const data=dataFrom();if(!validate(data))return;const same=deliveries.find(x=>normClient(x.cliente)===normClient(data.cliente));if(same&&!confirm(`${same.cliente} ya tiene la entrada N.º ${same.numero}. ¿Registrar otra igualmente?`))return;const btn=$("btn-entregar");btn.disabled=true;btn.textContent="Guardando…";try{await createDelivery(data);$("form-entrega").reset();$("e-dia").value=hoyISO();toggleDay();navigator.vibrate?.([70,40,100]);toast(navigator.onLine?"Entrega registrada y sincronizada.":"Entrega guardada. Se sincronizará al volver Internet.");$("e-cliente").focus();}catch(err){if(err.code==="duplicate")toast(`Ese número ya fue registrado${err.existing?.cliente?` a ${err.existing.cliente}`:""}.`,true);else{console.error(err);toast(errorMessage(err),true);}}finally{btn.disabled=false;btn.textContent="Registrar entrega";}}
function openEdit(id){const x=deliveries.find(d=>d.id===id);if(!x)return;editingId=id;$("edit-cliente").value=x.cliente;$("edit-numero").value=x.numero;$("edit-tipo").value=x.tipoAcceso;$("edit-dia").value=x.diaAcceso||hoyISO();toggleDay("edit-");$("modal-editar").showModal();}
async function submitEdit(e){e.preventDefault();const data=dataFrom("edit-");if(!validate(data,editingId))return;const prev=deliveries.find(x=>x.id===editingId);try{await updateDelivery(editingId,data,prev);$("modal-editar").close();toast("Entrega actualizada.");}catch(err){if(err.code==="duplicate")toast("Ese número ya está registrado.",true);else{console.error(err);toast(errorMessage(err),true);}}}
async function remove(id){const x=deliveries.find(d=>d.id===id);if(!x||!confirm(`¿Eliminar la entrada N.º ${x.numero} entregada a ${x.cliente}?`))return;try{await removeDelivery(id);toast("Entrega eliminada.");}catch(err){console.error(err);toast(errorMessage(err),true);}}
function exportCsv(){const rows=filtered();if(!rows.length){toast("No hay datos para exportar.",true);return;}const header=["Cliente","Numero","Tipo","Dia de acceso","Fecha de entrega","Hora"];const esc=v=>`"${String(v??"").replaceAll('"','""')}"`;const csv=[header,...rows.map(x=>[x.cliente,x.numero,x.tipoAcceso==="Libre"?"Pase libre":"Entrada de un día",x.tipoAcceso==="Dia"?formatDate(x.diaAcceso):"Todos los días",formatDate(x.fechaEntrega),x.horaEntrega||""])].map(r=>r.map(esc).join(";")).join("\n");downloadText(`entregas-rural-prado-${hoyISO()}.csv`,`\uFEFF${csv}`,"text/csv;charset=utf-8");}
function exportJson(){if(!deliveries.length){toast("No hay datos para respaldar.",true);return;}downloadText(`respaldo-entradas-${hoyISO()}.json`,JSON.stringify({app:"Control Entradas Rural del Prado 2026",exportadoEn:new Date().toISOString(),entregas:deliveries},null,2),"application/json");}
function detectLegacy(){try{const x=JSON.parse(localStorage.getItem(LEGACY_KEY)||"[]");$("btn-migrar").hidden=!Array.isArray(x)||!x.length;}catch{$("btn-migrar").hidden=true;}}
async function migrate(){let x=[];try{x=JSON.parse(localStorage.getItem(LEGACY_KEY)||"[]");}catch{}if(!x.length)return;if(!confirm(`Se encontraron ${x.length} registros anteriores. ¿Subirlos a Firebase?`))return;const r=await migrateLegacy(x);localStorage.setItem(`${LEGACY_KEY}_migrado`,JSON.stringify(x));localStorage.removeItem(LEGACY_KEY);detectLegacy();toast(`Migración lista: ${r.added} cargados y ${r.skipped} omitidos.`);}
function updateConnection(){const online=navigator.onLine;$("estado-conexion").classList.toggle("offline",!online);$("estado-conexion").querySelector(".estado-texto").textContent=online?"En línea":"Sin conexión";}
async function startScanner(){if(!("BarcodeDetector" in window)){toast("Este navegador no admite escaneo automático. Ingresá el número manualmente.",true);return;}try{cameraStream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:"environment"}},audio:false});$("scanner-video").srcObject=cameraStream;await $("scanner-video").play();$("modal-scanner").showModal();const detector=new BarcodeDetector({formats:["qr_code","code_128","ean_13","ean_8","upc_a","upc_e"]});scanTimer=setInterval(async()=>{try{const codes=await detector.detect($("scanner-video"));if(codes[0]?.rawValue){$("e-numero").value=codes[0].rawValue;closeScanner();toast("Código detectado.");}}catch{}},450);}catch{toast("No se pudo acceder a la cámara.",true);}}
function closeScanner(){clearInterval(scanTimer);cameraStream?.getTracks().forEach(t=>t.stop());cameraStream=null;if($("modal-scanner").open)$("modal-scanner").close();}

$("form-login").onsubmit=async e=>{e.preventDefault();const b=$("btn-login");b.disabled=true;b.textContent="Ingresando…";try{await login($("login-email").value.trim(),$("login-password").value);}catch(err){console.error(err);toast(errorMessage(err),true);}finally{b.disabled=false;b.textContent="Ingresar";}};
$("btn-salir").onclick=logout;$("form-entrega").onsubmit=submitNew;$("e-tipo").onchange=()=>toggleDay();$("edit-tipo").onchange=()=>toggleDay("edit-");$("form-editar").onsubmit=submitEdit;$("cancelar-edicion").onclick=()=>$("modal-editar").close();$("cancelar-edicion-2").onclick=()=>$("modal-editar").close();[$("buscar"),$("filtro-tipo"),$("filtro-fecha")].forEach(x=>x.oninput=renderTable);$("btn-limpiar-filtros").onclick=()=>{$("buscar").value="";$("filtro-tipo").value="Todos";$("filtro-fecha").value="";renderTable();};$("btn-exportar-csv").onclick=exportCsv;$("btn-exportar-json").onclick=exportJson;$("btn-migrar").onclick=migrate;$("btn-escanear").onclick=startScanner;$("cerrar-scanner").onclick=closeScanner;window.addEventListener("online",updateConnection);window.addEventListener("offline",updateConnection);window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();installPrompt=e;$("btn-instalar").hidden=false;});$("btn-instalar").onclick=async()=>{if(!installPrompt)return;await installPrompt.prompt();installPrompt=null;$("btn-instalar").hidden=true;};
observeAuth(user=>{if(stopWatch){stopWatch();stopWatch=null;}if(!user){$("pantalla-login").hidden=false;$("pantalla-app").hidden=true;return;}$("pantalla-login").hidden=true;$("pantalla-app").hidden=false;$("usuario-email").textContent=user.email||"Usuario";detectLegacy();stopWatch=watchDeliveries((rows,meta)=>{deliveries=sortedRows(rows);renderAll();if(meta.fromCache&&!navigator.onLine)updateConnection();},err=>{console.error(err);toast("No se pudo leer Firestore. Revisá las reglas.",true);});});
$("e-dia").value=hoyISO();toggleDay();updateConnection();if("serviceWorker" in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("./sw.js"));
