import { collection, deleteDoc, doc, getDoc, onSnapshot, serverTimestamp, setDoc, writeBatch } from "https://www.gstatic.com/firebasejs/12.16.0/firebase-firestore.js";
import { db } from "./firebase.js";
import { currentUser } from "./auth.js";
import { docIdForNumber, fechaLocal, normClient, normNumber } from "./utils.js";
const COLLECTION="entregas";
export function watchDeliveries(onData,onError){return onSnapshot(collection(db,COLLECTION),{includeMetadataChanges:true},snap=>{const rows=snap.docs.map(d=>({id:d.id,...d.data()}));onData(rows,snap.metadata);},onError);}
export async function createDelivery(data){const id=docIdForNumber(data.numero);const ref=doc(db,COLLECTION,id);const old=await getDoc(ref);if(old.exists())throw Object.assign(new Error("duplicate"),{code:"duplicate",existing:old.data()});const local=fechaLocal();await setDoc(ref,{cliente:data.cliente,clienteNorm:normClient(data.cliente),numero:data.numero,numeroNorm:normNumber(data.numero),tipoAcceso:data.tipo,diaAcceso:data.tipo==="Dia"?data.dia:"",fechaEntrega:local.fechaEntrega,horaEntrega:local.horaEntrega,creadoPor:currentUser()?.uid||"",creadoEn:serverTimestamp(),actualizadoEn:serverTimestamp()});}
export async function updateDelivery(currentId,data,previous){const newId=docIdForNumber(data.numero);const payload={cliente:data.cliente,clienteNorm:normClient(data.cliente),numero:data.numero,numeroNorm:normNumber(data.numero),tipoAcceso:data.tipo,diaAcceso:data.tipo==="Dia"?data.dia:"",actualizadoEn:serverTimestamp()};if(newId===currentId){await setDoc(doc(db,COLLECTION,currentId),payload,{merge:true});return;}const nextRef=doc(db,COLLECTION,newId);if((await getDoc(nextRef)).exists())throw Object.assign(new Error("duplicate"),{code:"duplicate"});const batch=writeBatch(db);batch.set(nextRef,{...previous,...payload,id:undefined});batch.delete(doc(db,COLLECTION,currentId));await batch.commit();}
export function removeDelivery(id){return deleteDoc(doc(db,COLLECTION,id));}
export async function migrateLegacy(items){let added=0,skipped=0;for(const x of items){try{const id=docIdForNumber(x.numero);const ref=doc(db,COLLECTION,id);if((await getDoc(ref)).exists()){skipped++;continue;}await setDoc(ref,{cliente:x.cliente,clienteNorm:normClient(x.cliente),numero:x.numero,numeroNorm:normNumber(x.numero),tipoAcceso:x.tipoAcceso||"Dia",diaAcceso:x.diaAcceso||"",fechaEntrega:x.fechaEntrega||fechaLocal().fechaEntrega,horaEntrega:x.horaEntrega||"",creadoPor:currentUser()?.uid||"",creadoEn:serverTimestamp(),actualizadoEn:serverTimestamp()});added++;}catch{skipped++;}}return {added,skipped};}
